import Header from '../components/Header';
import './globals.css';

export const metadata = {
	title: 'Expiry Reminder',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`antialiased`}>
				<Header />
				{children}
			</body>
		</html>
	);
}
